"""Initial tables

Revision ID: c392c323abc8
Revises: 
Create Date: 2026-06-07 20:35:28.587273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c392c323abc8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant', sa.Column('onboarding_stage', sa.Enum('BUSINESS_NAME', 'BUSINESS_TYPE', 'COMPLETED', name='onboardingstage'), nullable=False))
    op.create_index(op.f('ix_merchant_whatsapp_no'), 'merchant', ['whatsapp_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_whatsapp_no'), table_name='merchant')
    op.drop_column('merchant', 'onboarding_stage')
    # ### end Alembic commands ###
